server:
  port: ${sp.search}
spring:
  application:
    name: ${sn.search}
  elasticsearch:
    rest:
      uris: http://114.67.243.235:9200
      username: elasticsearch
      password: elasticsearch

